### ISSUE TITLE
Dark theme bug report

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#1047]
- [x] Avatar same problem as in  #1192
Accent colors parameter incorrect. 

- [ ] Dialog (check my comment - Gracjan)
Double check the color of boarder, it seems there are two different colors
<img width="253" alt="Screen Shot 2020-05-21 at 9 15 14 AM" src="https://user-images.githubusercontent.com/54589269/82562648-a9aca700-9b43-11ea-8775-be3c9237f974.png">

- [ ] Popover (check my comment - Gracjan)
Double check the color of boarder, it seems there are two different colors
<img width="454" alt="Screen Shot 2020-05-21 at 9 25 25 AM" src="https://user-images.githubusercontent.com/54589269/82563532-41f75b80-9b45-11ea-9886-e087d51e9018.png">

- [x] Status indicator - removed
The text color seems incorrect
<img width="231" alt="Screen Shot 2020-05-21 at 9 30 49 AM" src="https://user-images.githubusercontent.com/54589269/82563877-d19d0a00-9b45-11ea-86ac-cc2562c620ad.png">

**Comment by rengare** [comment]
@estelaxu3 @droshev 
When the dark theme is set to bar's subheader contains a shadow which overlaps border color. From specs The shadow should be set to 'null'
![image](https://user-images.githubusercontent.com/10849982/86771789-2099f280-c053-11ea-9899-8b9705448598.png)
![image](https://user-images.githubusercontent.com/10849982/86771953-622a9d80-c053-11ea-9130-3a6021a933b0.png)

**Comment by rengare** [comment]
@droshev @estelaxu3 
Dialog:
The problem is within box-shadow variable:
![image](https://user-images.githubusercontent.com/10849982/86773580-13cace00-c056-11ea-979d-d14f44275ffe.png)
![image](https://user-images.githubusercontent.com/10849982/86773719-3230c980-c056-11ea-8cb4-13a856672182.png)

I tried to fix it myself but the best way to solve it is to fix --sapContent_HeaderShadow value

**Comment by rengare** [comment]
https://github.com/SAP/fundamental-styles/issues/
