### ISSUE TITLE
CheckBox will crash the Chrome at version v83.0

### ISSUE THREAD

**Issue by Cyw1994** [SAP/fundamental-styles#1197]
#### Is this a bug, enhancement, or feature request?
This is a Bug.

#### Briefly describe your proposal.
The CheckBox module will crash the chrome when quickly click the box several times.

#### Which versions of Angular and Fundamental Library for Angular are affected? (If this is a feature request, use current version.)
Fundamental-For-Angular version: v0.14.0

#### If this is a bug, please provide steps for reproducing it.
1. Quickly click the checkbox several times.
2. The chrome will be 100% crashed.

#### Please provide relevant source code if applicable.
Not specific using case, just use the checkbox as sample code does.

#### Is there anything else we should know?
The Chrome error is `RESULT_CODE_UNINSTALL_USER_CANCEL`;
In fact you can directly reproduce it in the sample code page: [Checkbox-Module](https://sap.github.io/fundamental-ngx/#/core/checkbox)

**Comment by meganaconley** [comment]
This is due to the `::after` selector being added/removed rapidly when clicking the button. If the focus style is applied differently the issue does not occur.

Quick fork of the previous example: https://stackblitz.com/edit/angular-vltf4t-urjaqo?file=src%2Fstyles.scss
This example isn't perfect (for some reason the outline goes away on the checkbox after the first click) but you can now rapidly click the radio button and see there is no crash. Since removing the focus outline is unacceptable from an a11y standpoint, let's try to fix it by not using the `::after` selector instead.

**Comment by jbadan** [comment]
This is fixed in Chrome Version `86.0.4201.0`
