### ISSUE TITLE
Byline list with no border is adding 1rem to bottom and top padding

### ISSUE THREAD

**Issue by sKudum** [SAP/fundamental-styles#1564]
**Describe the bug**
Standard list with byline and no border is adding extra padding first children as so

> Is this issue related to a specific component?
Standard list with a byline and no border.

> What version of the Fundamental Library Styles are you using?
11.2rc

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Angular

**To Reproduce**
1). Add byline and no border class to list items.
2).On inspect, we have seen extra padding getting appended.
<img width="825" alt="2020-09-02_09-57-41" src="https://user-images.githubusercontent.com/53487468/91932376-9d6be480-ed03-11ea-9151-6b8ae08443ca.png">

**Expected behavior**
Should not add extra padding.

**Comment by InnaAtanasova** [comment]
Hey @sKudum it is the expected behaviour. A borderless list has the following specifications: 
<img width="794" alt="Screen Shot 2020-09-03 at 4 22 16 PM" src="https://user-images.githubusercontent.com/39598672/92163561-e99d4e80-ee01-11ea-9f01-0e7bc93c74d7.png">

The "inner" list items have padding-top and padding-bottom of 0.5rem. The first-child has padding-top: 1rem and the last child has padding-bottom: 1rem.
This is in styles:
<img width="1993" alt="Screen Shot 2020-09-03 at 4 23 26 PM" src="https://user-images.githubusercontent.com/39598672/92163674-15b8cf80-ee02-11ea-8958-7fbad4f96ac6.png">
<img width="2005" alt="Screen Shot 2020-09-03 at 4 23 14 PM" src="https://user-images.githubusercontent.com/39598672/92163682-17829300-ee02-11ea-8fff-46b5d6018dc9.png">
