### ISSUE TITLE
difference between fundamental and fundamental-styles?

### ISSUE THREAD

**Issue by mscudlik** [SAP/fundamental-styles#171]
what is the difference between https://github.com/SAP/fundamental/ and https://github.com/SAP/fundamental-styles/?

the look almost identical, having a guess i would say fundamental-styles replaces fundamental?
if so, please point that out

**Comment by droshev** [comment]
@mscudlik you are raising a very good question. I will try to answer you in a nutshell. I hope it won't be even more confusing 😀

The fundamental libraries are aiming to deliver the components for Fiori 3.0 as styling or native implementation in `react`, `angular`, or `vue`.

Fiori 3.0 is in progress and there are many updates coming along the way. Many updates that would be breaking changes for `fundamental-ui` as it is already in version 1. 
- One example is the SAP theming support.
- making the components' styling self-containing.
- better accessibility support.
- align closer to Fiori 3.0 design
In order to deliver this in a fast way, we decided to open a brand new library `fundamental-styles` and address all those new updates. 
At the same time `fundamental-ngx`, `fundamental-react`, `fundamental-vue` already switched to the new library.

Does this give a little bit bit clarity?

cheers,
deno

**Comment by MichaelSp** [comment]
Wouldn't it be helpful to have this more prominent in the projects `README`?
