### ISSUE TITLE
Action sheet icon and text are not aligned 

### ISSUE THREAD

**Issue by daisy-yovcheva** [SAP/fundamental-styles#1987]
**Describe the bug**

![Screen Shot 2020-12-18 at 1 34 57 PM](https://user-images.githubusercontent.com/72403541/102664057-ddca6380-4136-11eb-8905-6b5575425175.png)

Looking at the second action in the Action sheet: Pricing and Payment 
-There is more padding in the front of the dollar icon.
-Both icons and text are not aligned.

**Comment by mikerodonnell89** [comment]
> -There is more padding in the front of the dollar icon.

I think what's actually going on here is that the text/icons are center-aligned in the popover:  
![Screen Shot 2020-12-23 at 4 03 53 PM](https://user-images.githubusercontent.com/2471874/103042931-764a5480-4538-11eb-937a-1ef35914508d.png)

Re: the second point (Both icons and text are not aligned) - do you mean vertically, @daisy-yovcheva ? 

These are issues with the action sheet component not the wizard, so I have edited this issue appropriately

**Comment by InnaAtanasova** [comment]
Hi @daisy-yovcheva , in the latest releases of Fundamental-styles and Fundamental-ngx the issue is no longer reproducible.  
Action Sheet in Fundamental-styles:
<img width="431" alt="Screen Shot 2021-02-02 at 2 19 44 PM" src="https://user-images.githubusercontent.com/39598672/106651346-09c46b80-6562-11eb-8013-d14cf07825ab.png">

Wizard component with Action Sheet in Fundamental-ngx:
<img width="489" alt="Screen Shot 2021-02-02 at 2 20 38 PM" src="https://user-images.githubusercontent.com/39598672/106651432-21035900-6562-11eb-883b-2b5fdb95b9cb.png">
<img width="485" alt="Screen Shot 2021-02-02 at 2 20 27 PM" src="https://user-images.githubusercontent.com/39598672/106651437-22cd1c80-6562-11eb-8793-c683deb94b94.png">
