### ISSUE TITLE
Button split overwrites font color, even on semantic modes

### ISSUE THREAD

**Issue by JKMarkowski** [SAP/fundamental-styles#2163]
Screen taken from NGX:
![image](https://user-images.githubusercontent.com/26483208/109010101-abe1fa00-76af-11eb-91cc-f0b1df905d73.png)

It seems lkie `.fd-button-split__text` adds unnecessary color

**Comment by droshev** [comment]
@JKMarkowski how can we reproduce this?

**Comment by droshev** [comment]
seems fixed

**Comment by kavya-b** [comment]
in ngx, the problem was that the modifier `--emphasized` was not being applied at the `fd-button-split` parent level, also some hardcoded styles to fix the above issue made it seem like it was fixed. 
![image](https://user-images.githubusercontent.com/53509521/116507588-24964a00-a8dd-11eb-99b5-dbf7a4676748.png)

On applying the `--emphasized` modifier, the above issue looks fixed, but the rest of the buttons, like `positive`, don't have the correct color. Instead of green text, it has blue text:
![image](https://user-images.githubusercontent.com/53509521/116507851-bdc56080-a8dd-11eb-805d-d2bda4105bb9.png)

This is reproducible in Styles as well if we change the modifier of the 2nd button to `positive`:
<img width="325" alt="Screenshot 2021-04-29 at 11 14 56 AM" src="https://user-images.githubusercontent.com/53509521/116507927-e188a680-a8dd-11eb-878a-b8297710dd70.png">   <img width="308" alt="Screenshot 2021-04-29 at 11 15 06 AM" src="https://user-images.githubusercontent.com/53509521/116507919-ddf51f80-a8dd-11eb-90ae-2719498721e7.png">

I think this issue would need to be reopened. @droshev

**Comment by droshev** [comment]
I think everything behaves as designed - the emphasized split button doesn't have bold text
