### ISSUE TITLE
Card contents do not extend to the edge of the card

### ISSUE THREAD

**Issue by mikerodonnell89** [SAP/fundamental-styles#2348]
Here I have set the background of the card to blue, and if you inspect the element very closely you can see a white-ish gap between the left, right, and bottom of the blue and the edge of the card.  This is caused by the card having a transparent border, and the transparent border simply showing the color of the card below.  The card contents should extend to the edge of the card and abide by the card's border radii 

<img width="351" alt="Screen Shot 2021-05-11 at 3 08 54 PM" src="https://user-images.githubusercontent.com/2471874/117885219-d123e480-b26a-11eb-805c-9af223df5063.png">

**Comment by Smiranin** [comment]
@droshev @mikerodonnell89 I have investigated the issue. The root of the issue is border of `.fd-card`. I figure out that there is using `@sapTile_BorderColor` variable of `@sap-theming/theming-base-content` package and for some themes the border is not transparent. See screenshot
![2021-05-24_18-08](https://user-images.githubusercontent.com/14183958/119368165-5ec7f100-bcbb-11eb-825a-86abe93bda55.png)
So if we extend card contents to the edge of the card we will break some themes. 
If we need to hide border border  of `.fd-card` for some cases we can create extra class, with rule `border: none.` Or `margin: -1px ...` for card content and card header.

**Comment by droshev** [comment]
@I546502 maybe we can bring to the design team
