### ISSUE TITLE
Slider cursor does not have arrows (Morning Horizon)

### ISSUE THREAD

**Issue by obc514** [SAP/fundamental-styles#3805]
According to the [specs](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698915260), the slider cursor should have arrows (Morning Horizon)

**Comment by InnaAtanasova** [comment]
Hi @obc514 , we are aware of this discrepancy with the design specs. In order to add the arrows we need to introduce Breaking changes for the component and we decided not to do it. @droshev asked if it's possible to contact us in slack or teams so we can arrange a quick meeting and discuss more the issues you created and answer all your questions about Horizon theming in Fund-styles. Thank you!

**Comment by droshev** [comment]
Let's keep the current implementation as is as nothing as functionality is missing atm and the design may keep evolving further. (agreed with and aligned with CX)
