### ISSUE TITLE
Enhancement: revisit 'compact' mode selectors.

### ISSUE THREAD

**Issue by N1XUS** [SAP/fundamental-styles#4273]
Current overview of handing 'compact' state:
- Unique class based on BEM technique is needed for every component;
- Some components uses 'compact' selector for inner elements and not for the root one;
- Libraries that uses fundamental-styles (e.g. fundamental-ngx) required to adjust their library code to follow this logic.

On the other hand, we have 'state' modifier, which are not following this technique:
- we have `is-selected`, `is-focus`, `is-hover`, `is-warning`, etc. modifier classes that do not follow BEM logic, and easy to use with almost any component since they are **generic**.

The proposition is to: introduce `.is-compact`, `is-cozy` and `is-condensed` classes which is assigned to the root of the component if needed.
Three of them make sense for cases when root component is compact, inner is cozy and inner's child is condensed. This way we would still keep the unique content density state for each component, yet, if we follow the same logic we have with `fd-rtl()` mixin, we would need to specify `.is-compact` only **once** per root component, and all child elements would follow it, if no `is-cozy` or `fd-condensed` classes applied to child elements.

**Comment by g-cheishvili** [comment]
This can make ngx content density management way easier, currently, the content density is done the way it is because every component has its own approach to the content density, naming and application logic. If we move forward with same names for determining modes, then we can go with only the CSS variables, which potentially can reduce the sizes
