### ISSUE TITLE
visual automation test differente browsers

### ISSUE THREAD

**Issue by droshev** [SAP/fundamental-styles#448]
The current implementation of the test script runs only for Chrome. The goal is to make the script running other browsers (IE11, Edge, FF, SF)

**Comment by OlegsPesudovs** [comment]
Greetings @droshev ,
Looked a bit into this topic..
from BackstopJS docs, git and dev/user comments, currently only chrome is supported officially with Chromy and Puppeteer engines. 

It should be however possible to create a custom runner with some other engine for other browser, like SlimerJS, for firefox or TrifleJS, for IE. 
There is a BackstopJS branch engineOptionsUpdate (https://github.com/garris/BackstopJS/tree/engineOptionsUpdate) that was worked on to add SlimerJS for Firefox testing and I would recommend taking a look into it, but there are some changes to how BackstopJS works and would require a bit of adjusting. Sadly I was unable to run slimer on that branch due to some compatibility issue with my setup.

Please let me know what you think.
