### ISSUE TITLE
Feature Request: Allow sizing of Modal via property instead of CSS

### ISSUE THREAD

**Issue by JaySardhara** [SAP/fundamental-styles#457]
Can we have a property in Modal where we can provide sizing ? 
It would be easier to render small/medium/large Modal instead of tweaking CSS of Modal.

Similar to https://react-bootstrap.github.io/components/modal/#modal-default-sizing
![image](https://user-images.githubusercontent.com/6151138/69453366-9f3a5d80-0d18-11ea-9d05-c9bd53637adb.png)

**Comment by salarenko** [comment]
@jbadan I know that creating predefined sizes of modal seems to be more intuitive to be done on Fundamental Styles side, but Fiori3 design doesn't specify any predefined sizes. Since Fundamental Styles should be pure Fiori3 I'd suggest moving this feature request to libraries implementing components based on Fundamental Styles.

**Comment by droshev** [comment]
Closing this issue as there isn't much we can offer from Fiori 3 point of view.
