### ISSUE TITLE
Form radio broken in IE

### ISSUE THREAD

**Issue by estelaxu3** [SAP/fundamental-styles#481]
Missing colors in form radio button.

**Comment by estelaxu3** [comment]
![image](https://user-images.githubusercontent.com/54589269/70248599-1f18ec80-1749-11ea-951e-7acb915dead4.png)

The colored circle is off center.

**Comment by estelaxu3** [comment]
![image](https://user-images.githubusercontent.com/54589269/70250096-5f796a00-174b-11ea-8e35-418cf30028c6.png)

**Comment by salarenko** [comment]
Issue appears also on Edge - Resolution 1920x1080p

![image](https://user-images.githubusercontent.com/17496353/70311764-91a1cf00-1812-11ea-83f8-91e0eb3143c3.png)

**Comment by salarenko** [comment]
Our current solution is based on using `input::after` element to create a custom styling for a radio button. Unfortunately such implementation doesn't work for IE11 due to the browser not supporting pseudo-elements on HTML input tags.

A common solution of this problem is using `label::before` and `label::after` pseudo-elements for visualizing checkbox and its checked state. Such implementation will provide cross browser solution for custom styling of the radio-buttons and check-boxes (unfortunately visual bugs appear also on Edge and Safari) and most importantly still support native checkbox input behavior (keyboard navigation and manipulation of the inputs state).

To get familiar with this solution I recommend checking [this link](https://scottaohara.github.io/a11y_styled_form_controls/src/radio-button/) (section "1. Visually Hidden Radios") and investigating the implementation.
