### ISSUE TITLE
Input Groups do not meet the a11y requirements for 44px touchable area in cosy mode

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#658]
In the current implementation of Input Groups we do not meet the a11y requirements for 44px touchable area in cosy mode. The height of the element now including the border is 38px. 
<img width="1105" alt="Screen Shot 2020-02-13 at 11 37 40 AM" src="https://user-images.githubusercontent.com/39598672/74456788-5a285200-4e55-11ea-9b88-017ae91b0701.png">

**Comment by droshev** [comment]
@estelaxu3 can you follow up on this?

**Comment by estelaxu3** [comment]
I followed up with designer and waiting for the feedback.

**Comment by droshev** [comment]
@estelaxu3 any update?

**Comment by estelaxu3** [comment]
I forwarded Erico's comment about the accessibility in email.

**Comment by estelaxu3** [comment]
This is what Erico suggested to address this issue:
My suggestion for this component (without having a more detailed evaluation of the use-case specifics) would be one of the following:

- Going a similar route as the Step Input control (if the Input Field is small enough to allow for the user to comfortably click on either side button without having to move the pointer all the way across the screen each time):

![image001](https://user-images.githubusercontent.com/54589269/85886579-3679fe80-b79b-11ea-95af-7496dd300948.png)

- Using an Input Field with Buttons, and rather than having the two arrows on top of each other (which might lead to more frequent user-error due to their size), having them as side-by-side Buttons, to the right of the Input Field (please note that Buttons within Input Fields must be stripped out of their “touch containers”):

![image002](https://user-images.githubusercontent.com/54589269/85886597-3b3eb280-b79b-11ea-9a39-c43a44dd0022.png)
