### ISSUE TITLE
Refactor/Remove Inline Help to match Fiori 3 specs and the sap-theming 

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#736]
Inline Help does not have an equivalent component in Fiori3. We need to decide if we keep it or deprecate it. If we decide to keep it we should migrate the colors to sap-theming variables

**Comment by droshev** [comment]
@estelaxu3 do you think you can help here?

**Comment by estelaxu3** [comment]
First of all, I think we should keep it because it is heavily used by C4 teams. 
Second, from accessibility perspective, I think we should also change how the inline question icon behave when it is interacted. When inline help is in its default, it should be transparent. When it is clicked or hover, it should turn grey or blue (SAP active blue) so that users would know that there is an interaction going on. 
<img width="285" alt="Screen Shot 2020-03-30 at 3 47 13 PM" src="https://user-images.githubusercontent.com/54589269/77955176-be846100-729d-11ea-961f-e08106f23258.png">

**Comment by estelaxu3** [comment]
Design suggestion:
For the inline icon, we could use the [Button](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2025039257) approach in Fiori:
<img width="211" alt="Screen Shot 2020-07-07 at 6 54 02 AM" src="https://user-images.githubusercontent.com/54589269/86791884-d0a13880-c01e-11ea-973e-069d47e58259.png">

When click down or hover on the question icon, it changes color. It helps with notifying user there is action going on:
<img width="527" alt="Screen Shot 2020-07-07 at 6 54 06 AM" src="https://user-images.githubusercontent.com/54589269/86792096-ff1f1380-c01e-11ea-80ec-dee98f42d59c.png">

Icon code: 
Regular & diable: xe1c4
Down: xe1c3

**Comment by prsdthkr** [comment]
@estelaxu3 may I suggest a focus state here for when the keyboard focus is on this button.

Focused 
![image](https://user-images.githubusercontent.com/43764832/87484182-65d99980-c5ea-11ea-9c05-59f727c970d9.png)

**Comment by InnaAtanasova** [comment]
We removed this component from fund-styles
