### ISSUE TITLE
Refactor StepInput to match Fiori 3 specs

### ISSUE THREAD

**Issue by InnaAtanasova** [SAP/fundamental-styles#779]
The StepInput pattern in Fundamental styles should be refactored to match the Fiori3 specs. This might require creating a StepInput component. Currently it's a pattern since it's composed by other components and doesn't have specific classes. 

Current implementation can be found  [here](https://deploy-preview-770--fundamental-styles.netlify.com/patterns/step-input.html)

**Comment by prsdthkr** [comment]
It think it is because of the [Fiori 3 spec](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2048477546), but the focus ring is not visible on the individual step up and step down buttons as seen in the patterns example. I can see this becoming an accessibility issue.

Patterns example shows focus ring on individual buttons:
![image](https://user-images.githubusercontent.com/43764832/81961400-2b8e5480-95c7-11ea-8e07-6fe898064489.png)


![image](https://user-images.githubusercontent.com/43764832/81961469-4791f600-95c7-11ea-9988-b2efa765e17c.png)
